### ISSUE TITLE
System.Net.ProtocolViolationException

### ISSUE THREAD

**Issue by jmcglory** [betfair/API-NG-sample-code#16]
This app was working fine for me until a few weeks (?) ago it stopped working. Happens in networkClient.Invoke method called in ListMarketCatalogue(). I have tried to step through but cant suss it out. I havent changed any code, I dont understand why it stopped working.

System.Net.ProtocolViolationException: You must write ContentLength bytes to the request stream before calling [Begin]GetResponse.
   at System.Net.HttpWebRequest.BeginGetResponse(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at BetfairNG.Network.<>c__DisplayClass8.<Request>b__5(Task`1 stream)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at BetfairNG.Network.<>c__DisplayClass2`1.<Invoke>b__1(Task`1 c)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.Net.ProtocolViolationException: You must write ContentLength bytes to the request stream before calling [Begin]GetResponse.
   at System.Net.HttpWebRequest.BeginGetResponse(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at BetfairNG.Network.<>c__DisplayClass8.<Request>b__5(Task`1 stream)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by mrtdoulaty** [comment]
Try setting
System.Net.ServicePointManager.Expect100Continue = false; 

(if you're interested to know what that does, check this http://blog.mrt-web.com/2009/06/request-failed-with-http-status-417.html )

**Comment by jmcglory** [comment]
Thank you, that works. I should have checked their release notes as this is detailed on 27th July 15

Thanks again
